# Generated by Django 5.1.4 on 2025-03-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_alter_comment_options_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_name',
            new_name='parent_comment',
        ),
    ]
